name: build-and-publish

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run test:ci
      - name: 'Release'
        if: github.ref == 'refs/heads/master' && matrix.node-version == '14.x'
        run: npx semantic-release
        env:
          CI: true
          NPM_TOKEN: ${{secrets.npm_token}}
          GH_TOKEN: ${{secrets.gh_token}}
